### ISSUE TITLE
Question on Masking

### ISSUE THREAD

**Issue by sclincha** [Guillem96/pointer-nn-pytorch#1]
Hi,
 Thanks a lot for your details explanation: however, it seems that your implementation does not mask element already picked at previous steps, i.e. the attention should be masked for elements already chosen.
 Is this correct or am I missing something in your code ?

**Comment by bberabi11** [comment]
Hi, 
Thanks for your work. It clarified a lot of details for me. However, I believe that your attention module is not the relevant case for the Pointer Network. What you implemented corresponds to the "Content based input attention" in the paper, but this is not the one pointer network uses. According to my understanding d prime is not calculated in the pointer network. Can it be that you mixed the two cases up ?
