### ISSUE TITLE
Possible mistake in attention mechanism

### ISSUE THREAD

**Issue by ghost** [Guillem96/pointer-nn-pytorch#2]
Hi,
Thanks for your work. It clarified a lot of details for me. However, I believe that your attention module is not the relevant case for the Pointer Network. What you implemented corresponds to the "Content based input attention" in the paper, but this is not the one pointer network uses. According to my understanding d prime is not calculated in the pointer network. Can it be that you mixed the two cases up ?

**Comment by ngoodger** [comment]
Hey,  I wondered about this too.  I guess including d prime shouldn't hurt and might help the decoder?  I'll try to test and write back if I find anything.
